### ISSUE TITLE
Website link not working

### ISSUE THREAD

**Issue by murali1996** [cambridgeltl/cometa#2]
Hey, thanks for the great work. I am interested to check out your dataset. However, the website link: https://siphs.org/corpus isn't working. Could you provide me a way to obtain this dataset?

**Comment by sap218** [comment]
+1

**Comment by hardyqr** [comment]
Sorry that the website server has been down and we are contacting staffs in the university to fix it. For now please contact Professor Nigel Collier (nhc30@cam.ac.uk) or me (fl399@cam.ac.uk) for a copy of the corpus. Thanks!

**Comment by sap218** [comment]
Hi @hardyqr - I did contact Professor Collier for a copy of the corpus around 3/4 weeks ago but I didn't get a response.

**Comment by HeglerTissot** [comment]
Any idea when the corpus will be available for download again?

**Comment by hardyqr** [comment]
> Any idea when the corpus will be available for download again?

Hi @HeglerTissot, sorry for the inconvenience -- could you please send me an email (to fl399@cam.ac.uk)? I will share the corpus.

**Comment by hardyqr** [comment]
Dataset released with dropbox.

**Comment by hardyqr** [comment]
Dataset released with dropbox.
