### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by fredymad** [cambridgeltl/cometa#4]
Hello,

Dropbox link is down. Can you provide an alternative download linke for COMETA corpus?

Thanks

**Comment by komi786** [comment]
I couldn't find link to download COMETA corpus.. @fredymad did you manage to find it?

**Comment by hardyqr** [comment]
Hi both, I've updated the download links to also include a google drive one. Let me know if it still doesn't work. Thanks.

**Comment by fredymad** [comment]
It is working, thank you so much @komi786 @hardyqr
